import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'fr' | 'ar' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.login': 'Log in',
    'nav.register': 'Register',
    'nav.dashboard': 'Home',
    'nav.likelemba': 'Likelemba',
    'nav.members': 'Members',
    'nav.payoutHistory': 'Payout History',
    'nav.logout': 'Log out',

    'home.title': 'Build Your Future Through',
    'home.titleHighlight': 'Collective Savings',
    'home.subtitle': 'Likelemba brings communities together through traditional rotating savings and credit associations. Save together, grow together, succeed together.',
    'home.getStarted': 'Get Started',
    'home.learnMore': 'Learn More',
    'home.whyChoose': 'Why Choose Likelemba?',
    'home.whySubtitle': 'Experience the power of community-based savings with modern technology',
    'home.easyManagement': 'Easy Management',
    'home.easyManagementDesc': 'Create and manage your savings groups with an intuitive interface. Track payments, schedules, and members effortlessly.',
    'home.communityDriven': 'Community Driven',
    'home.communityDrivenDesc': 'Build stronger communities through collective financial goals. Support each other while achieving individual objectives.',
    'home.secureReliable': 'Secure & Reliable',
    'home.secureReliableDesc': 'Your data is protected with enterprise-grade security. Transparent tracking ensures accountability for all members.',
    'home.readyToStart': 'Ready to Start Saving?',
    'home.readySubtitle': 'Join thousands of people using Likelemba to achieve their financial goals through community savings.',
    'home.createAccount': 'Create Your Account',
    'home.howItWorks': 'How It Works',
    'home.howItWorksSubtitle': 'Simple steps to start your savings journey',
    'home.step1': 'Create Group',
    'home.step1Desc': 'Set up your savings group with custom parameters',
    'home.step2': 'Add Members',
    'home.step2Desc': 'Invite participants to join your Likelemba',
    'home.step3': 'Contribute',
    'home.step3Desc': 'Members make regular contributions as scheduled',
    'home.step4': 'Receive Payout',
    'home.step4Desc': 'Each member receives the full amount in turn',
    'home.visitors': 'visitors',

    'about.title': 'About Likelemba',
    'about.subtitle': 'Empowering communities through traditional savings practices enhanced by modern technology',
    'about.whatIs': 'What is Likelemba?',
    'about.whatIsDesc1': 'Likelemba is a digital platform that modernizes the traditional African rotating savings and credit association (ROSCA) system. The name "Likelemba" comes from the Lingala word for a communal savings group, a practice deeply rooted in African culture.',
    'about.whatIsDesc2': 'In a Likelemba, a group of people come together and contribute a fixed amount regularly. Each cycle, one member receives the total collected amount until everyone has benefited. This system builds trust, encourages savings, and provides access to larger sums of money without traditional banking requirements.',
    'about.whatIsDesc3': 'Our platform brings this time-tested practice into the digital age, making it easier to manage, more transparent, and accessible to communities around the world.',
    'about.mission': 'Our Mission',
    'about.missionDesc': 'To provide accessible, transparent, and efficient tools that strengthen community bonds while helping individuals achieve their financial goals through collective savings.',
    'about.objectives': 'Our Objectives',
    'about.objective1': 'Digitize traditional savings practices',
    'about.objective2': 'Increase financial inclusion',
    'about.objective3': 'Build stronger communities',
    'about.objective4': 'Ensure transparency and trust',
    'about.values': 'Our Values',
    'about.communityFirst': 'Community First',
    'about.communityFirstDesc': 'We believe in the power of communities working together towards common goals.',
    'about.transparency': 'Transparency',
    'about.transparencyDesc': 'Every transaction and schedule is visible to all group members, building trust.',
    'about.accessibility': 'Accessibility',
    'about.accessibilityDesc': 'We make financial tools available to everyone, regardless of banking access.',
    'about.culturalRespect': 'Cultural Respect',
    'about.culturalRespectDesc': 'We honor traditional practices while embracing modern technology.',
    'about.security': 'Security',
    'about.securityDesc': 'Your data and information are protected with enterprise-grade security.',
    'about.empowerment': 'Empowerment',
    'about.empowermentDesc': 'We provide tools that help individuals and communities take control of their finances.',
    'about.joinCommunity': 'Join Our Community',
    'about.joinCommunityDesc': 'Be part of a movement that\'s transforming how communities save and support each other.',
    'about.getStartedToday': 'Get Started Today',

    'contact.title': 'Get in Touch',
    'contact.subtitle': 'Have questions? We\'d love to hear from you.',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.sendMessage': 'Send us a Message',
    'contact.fullName': 'Full Name',
    'contact.emailAddress': 'Email Address',
    'contact.phoneNumber': 'Phone Number',
    'contact.optional': 'Optional',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us how we can help...',
    'contact.sendButton': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.successMessage': 'Thank you for your message! We\'ll get back to you soon.',

    'login.title': 'Welcome Back',
    'login.subtitle': 'Sign in to your Likelemba account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.noAccount': 'Don\'t have an account?',
    'login.registerHere': 'Register here',

    'register.title': 'Create Account',
    'register.subtitle': 'Join Likelemba and start saving together',
    'register.fullName': 'Full Name',
    'register.email': 'Email Address',
    'register.password': 'Password',
    'register.passwordRequirement': 'At least 6 characters',
    'register.confirmPassword': 'Confirm Password',
    'register.reenterPassword': 'Re-enter your password',
    'register.createAccount': 'Create Account',
    'register.creating': 'Creating account...',
    'register.hasAccount': 'Already have an account?',
    'register.signIn': 'Sign in',
    'register.successMessage': 'Account created successfully! Please check your email to confirm your account. Redirecting to login...',

    'forgotPassword.title': 'Forgot Password',
    'forgotPassword.subtitle': 'Enter your email to receive a password reset link',
    'forgotPassword.email': 'Email Address',
    'forgotPassword.sendLink': 'Send Reset Link',
    'forgotPassword.sending': 'Sending...',
    'forgotPassword.backToLogin': 'Back to Login',
    'forgotPassword.successMessage': 'Password reset link has been sent to your email. Please check your inbox and follow the instructions.',

    'resetPassword.title': 'Reset Password',
    'resetPassword.subtitle': 'Enter your new password below',
    'resetPassword.newPassword': 'New Password',
    'resetPassword.confirmPassword': 'Confirm Password',
    'resetPassword.passwordHint': 'Must be at least 6 characters',
    'resetPassword.updatePassword': 'Update Password',
    'resetPassword.updating': 'Updating...',
    'resetPassword.successMessage': 'Password updated successfully!',
    'resetPassword.redirecting': 'Redirecting to login...',

    'confirmEmail.verifying': 'Verifying your email...',
    'confirmEmail.pleaseWait': 'Please wait while we confirm your email address',
    'confirmEmail.success': 'Email Confirmed!',
    'confirmEmail.successMessage': 'Your email has been successfully confirmed. You can now log in to your account.',
    'confirmEmail.redirecting': 'Redirecting to login page...',
    'confirmEmail.error': 'Confirmation Failed',
    'confirmEmail.errorMessage': 'There was an error confirming your email address.',
    'confirmEmail.goToLogin': 'Go to Login',

    'dashboard.welcome': 'Welcome',
    'dashboard.totalGroups': 'Total Groups',
    'dashboard.activeGroups': 'Active Groups',
    'dashboard.totalMembers': 'Total Members',
    'dashboard.mamanStatus': 'Maman Likelemba Status',
    'dashboard.mamanStatusDesc': 'You are a primary member and can manage Likelemba groups for your community.',
    'dashboard.yourGroups': 'Your Likelemba Groups',
    'dashboard.createGroup': 'Create Group',
    'dashboard.noGroups': 'No Groups Yet',
    'dashboard.noGroupsDesc': 'Create your first Likelemba group to get started',
    'dashboard.createFirstGroup': 'Create Your First Group',
    'dashboard.members': 'members',
    'dashboard.perMember': 'per member',
    'dashboard.started': 'Started',
    'dashboard.viewMembers': 'View Members',
    'dashboard.loading': 'Loading groups...',
    'dashboard.edit': 'Edit',
    'dashboard.delete': 'Delete',
    'dashboard.share': 'Share',
    'dashboard.editGroup': 'Edit Group',
    'dashboard.deleteGroup': 'Delete Group',
    'dashboard.groupName': 'Group Name',
    'dashboard.amountPerMember': 'Amount per Member ($)',
    'dashboard.paymentFrequency': 'Payment Frequency',
    'dashboard.paymentMethod': 'Payment Method',
    'dashboard.status': 'Status',
    'dashboard.active': 'Active',
    'dashboard.completed': 'Completed',
    'dashboard.paused': 'Paused',
    'dashboard.bankTransfer': 'Bank Transfer',
    'dashboard.saving': 'Saving...',
    'dashboard.deleteConfirm': 'Are you sure you want to delete the group',
    'dashboard.deleteWarning': '⚠️ This action is irreversible. All members, payments, and history will be deleted.',
    'dashboard.typeToConfirm': 'To confirm, type the group name:',
    'dashboard.deleting': 'Deleting...',
    'dashboard.deletePermanently': 'Delete Permanently',

    'profile.title': 'My Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.emailNote': 'Email cannot be changed',
    'profile.phone': 'Phone',
    'profile.address': 'Address',
    'profile.saveChanges': 'Save Changes',
    'profile.clickToChange': 'Click the icon to change the photo',
    'profile.maxSize': 'Max 2MB • JPG, PNG',
    'profile.uploading': 'Uploading...',
    'profile.dangerZone': 'Danger Zone',
    'profile.deleteAccount': 'Delete My Account',
    'profile.deleteWarning': 'Deleting your account is permanent and cannot be undone. All your data will be permanently deleted.',
    'profile.deleteConfirmTitle': 'Confirm Deletion',
    'profile.deleteConfirmText': 'This action is irreversible. All your data, groups, and history will be permanently deleted.',
    'profile.typeDELETE': 'To confirm, type DELETE below:',
    'profile.deletingAccount': 'Deleting...',

    'likelemba.title': 'Create Likelemba Group',
    'likelemba.subtitle': 'Set up a new savings group for your community',
    'likelemba.groupName': 'Group Name',
    'likelemba.groupNamePlaceholder': 'e.g., Community Savings Group',
    'likelemba.numberOfMembers': 'Number of Members',
    'likelemba.amountPerMember': 'Amount per Member ($)',
    'likelemba.paymentFrequency': 'Payment Frequency',
    'likelemba.daily': 'Daily',
    'likelemba.weekly': 'Weekly',
    'likelemba.monthly': 'Monthly',
    'likelemba.paymentMethod': 'Payment Method',
    'likelemba.interac': 'Interac',
    'likelemba.cash': 'Cash',
    'likelemba.startDate': 'Start Date',
    'likelemba.endDate': 'End Date',
    'likelemba.summary': 'Summary',
    'likelemba.totalPerCycle': 'Total per cycle:',
    'likelemba.serviceFee': 'Service fee (one-time):',
    'likelemba.receiveNote': 'Each member will receive',
    'likelemba.whenTurn': 'when it\'s their turn',
    'likelemba.createButton': 'Create Group',
    'likelemba.creating': 'Creating...',

    'members.title': 'Members',
    'members.noGroupSelected': 'No Group Selected',
    'members.selectGroup': 'Please select a group from your dashboard',
    'members.addMember': 'Add Member',
    'members.noMembers': 'No members yet',
    'members.addFirstMember': 'Add First Member',
    'members.position': 'Position',
    'members.contribution': 'contribution',
    'members.paid': 'Paid',
    'members.recordPayment': 'Record Payment',
    'members.processing': 'Processing...',
    'members.editMember': 'Edit Member',
    'members.fullName': 'Full Name',
    'members.email': 'Email',
    'members.phone': 'Phone',
    'members.address': 'Address',
    'members.membershipAmount': 'Membership Amount ($)',
    'members.receiptOrder': 'Receipt Order',
    'members.cancel': 'Cancel',
    'members.update': 'Update Member',
    'members.add': 'Add Member',
    'members.cycle': 'Cycle',
    'members.nextPayment': 'Next payment:',
    'members.loading': 'Loading...',

    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',

    'payment.title': 'Payment Tracking',
    'payment.contributions': 'Contributions',
    'payment.totalPaid': 'Total Paid',
    'payment.ofPayments': 'of {total} payments',
    'payment.completion': 'Completion',
    'payment.overallProgress': 'overall progress',
    'payment.periods': 'Periods',
    'payment.cycles': 'cycles',
    'payment.current': 'Current',
    'payment.cycle': 'Cycle',
    'payment.paid': 'paid',
    'payment.markPaid': 'Mark Paid',
    'payment.sending': 'Sending...',
    'payment.remind': 'Remind',
    'payment.sent': 'Sent',
    'payment.noGroupSelected': 'No Group Selected',
    'payment.selectGroup': 'Please select a group from your dashboard',
    'payment.noPeriods': 'No payment periods found for this group',
    'payment.daily': 'Daily',
    'payment.weekly': 'Weekly',
    'payment.monthly': 'Monthly',
    'payment.reminderSent': 'Reminder sent to {name}',
    'payment.reminderFailed': 'Failed to send reminder',
    'payment.updateFailed': 'Failed to update payment status',

    'shared.invalidLink': 'Invalid share link',
    'shared.notFound': 'Group not found or link has expired',
    'shared.loadFailed': 'Failed to load group data',
    'shared.paymentsTitle': 'Members & Payments',
    'shared.noPayments': 'No payments recorded',
    'shared.sharedBy': 'This link was shared by the Likelemba group manager',

    'search.placeholder': 'Search groups...',
    'search.noResults': 'No groups found',
    'search.tryAdjusting': 'Try adjusting your search query',

    'nav.profile': 'Profile',
    'nav.paymentTracking': 'Payment Tracking',

    'share.buttonText': 'Share',
    'share.title': 'Share Group',
    'share.description': 'Share this link with your group members. They will be able to see all members and payment history.',
    'share.activeLink': 'Active share link',
    'share.copied': 'Copied!',
    'share.copyLink': 'Copy Link',
    'share.generateNew': 'Generate New Link',
    'share.generating': 'Generating...',
    'share.generate': 'Generate Share Link',
    'share.warning': '💡 This link allows anyone to view the group information and payment history. Only share it with your group members.',
    'share.error': 'Error creating share link',

    'notification.title': 'Payment Reminders',
    'notification.unread': '{count} unread notification',
    'notification.unreadPlural': '{count} unread notifications',
    'notification.dismiss': 'Dismiss',
    'notification.cycle': 'Cycle {number}',
    'notification.payTo': 'Pay {name}',
    'notification.markRead': 'Mark as read',
    'notification.showLess': 'Show less',
    'notification.showMore': 'Show {count} more',
    'notification.today': 'Today',
    'notification.tomorrow': 'Tomorrow',

    'footer.copyright': 'All rights reserved.',
    'footer.tagline': 'Building communities through collective savings',

    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Get instant answers to your questions about Likelemba',
    'faq.aiAssistant': 'AI Assistant',
    'faq.askPlaceholder': 'Ask me anything about Likelemba...',
    'faq.ask': 'Ask',
    'faq.asking': 'Asking...',
    'faq.loginPrompt': 'Log in to save your conversation history and get personalized answers',
    'faq.showChat': 'Show Chat History',
    'faq.hideChat': 'Hide Chat',
    'faq.thinking': 'Thinking...',
    'faq.wasHelpful': 'Was this helpful?',
    'faq.browseFAQs': 'Browse FAQs',
    'faq.searchPlaceholder': 'Search FAQs...',
    'faq.all': 'All',
    'faq.noResults': 'No FAQs found matching your search',
    'faq.stillQuestions': 'Still have questions?',
    'faq.contactSupport': 'Contact Support',

    'payoutHistory.title': 'Payout History',
    'payoutHistory.subtitle': 'Track which members have received their payouts in each cycle',
    'payoutHistory.selectGroup': 'Select Group',
    'payoutHistory.members': 'members',
    'payoutHistory.noGroups': 'No groups found',
    'payoutHistory.noGroupsDesc': 'Create a Likelemba group to start tracking payouts',
    'payoutHistory.noCycles': 'No cycles yet',
    'payoutHistory.noCyclesDesc': 'Payment cycles will appear here once your group starts',
    'payoutHistory.cycle': 'Cycle',
    'payoutHistory.beneficiary': 'Beneficiary',
    'payoutHistory.paymentDate': 'Payment Date',
    'payoutHistory.totalAmount': 'Total Amount',
    'payoutHistory.contributions': 'Contributions',
    'payoutHistory.status': 'Status',
    'payoutHistory.completed': 'Completed',
    'payoutHistory.pending': 'Pending',
    'payoutHistory.overdue': 'Overdue',
    'payoutHistory.howItWorks': 'How Payout History Works',
    'payoutHistory.howItWorksLine1': 'Each cycle represents one round of contributions where one member receives the total collected amount',
    'payoutHistory.howItWorksLine2': 'The beneficiary is determined by the receipt order set when the group was created',
    'payoutHistory.howItWorksLine3': 'Contributions shows how many members have paid for that cycle',
    'payoutHistory.howItWorksLine4': 'Status shows whether the payout is completed, pending, or overdue',

    'admin.nav.dashboard': 'Dashboard',
    'admin.nav.users': 'Users',
    'admin.nav.groups': 'Groups',
    'admin.nav.messages': 'Messages',
    'admin.nav.activity': 'Activity Log',
    'admin.nav.settings': 'Settings',
    'admin.nav.userView': 'User View',

    'admin.dashboard.title': 'Admin Dashboard',
    'admin.dashboard.subtitle': 'Overview of platform statistics and activity',
    'admin.dashboard.totalUsers': 'Total Users',
    'admin.dashboard.totalGroups': 'Total Groups',
    'admin.dashboard.totalRevenue': 'Total Revenue',
    'admin.dashboard.pendingMessages': 'Pending Messages',
    'admin.dashboard.active': 'active',
    'admin.dashboard.serviceFees': 'Service fees collected',
    'admin.dashboard.needsResponse': 'needs response',
    'admin.dashboard.recentActivity': 'Recent Activity',
    'admin.dashboard.noActivity': 'No recent activity',
    'admin.dashboard.systemHealth': 'System Health',
    'admin.dashboard.databaseStatus': 'Database Status',
    'admin.dashboard.apiStatus': 'API Status',
    'admin.dashboard.operational': 'Operational',
    'admin.dashboard.highMessageVolume': 'High Message Volume',
    'admin.dashboard.attention': 'Attention Required',

    'admin.users.title': 'User Management',
    'admin.users.subtitle': 'Manage all platform users',
    'admin.users.searchPlaceholder': 'Search by name or email...',
    'admin.users.allStatuses': 'All Statuses',
    'admin.users.active': 'Active',
    'admin.users.suspended': 'Suspended',
    'admin.users.banned': 'Banned',
    'admin.users.user': 'User',
    'admin.users.contact': 'Contact',
    'admin.users.role': 'Role',
    'admin.users.status': 'Status',
    'admin.users.joined': 'Joined',
    'admin.users.actions': 'Actions',
    'admin.users.organizer': 'Organizer',
    'admin.users.member': 'Member',
    'admin.users.noUsers': 'No users found',
    'admin.users.note': 'Note',
    'admin.users.noteText': 'Changing a user status will affect their ability to access the platform',

    'admin.groups.title': 'Group Management',
    'admin.groups.subtitle': 'Monitor all Likelemba groups',
    'admin.groups.searchPlaceholder': 'Search by group name or creator...',
    'admin.groups.allStatuses': 'All Statuses',
    'admin.groups.active': 'Active',
    'admin.groups.paused': 'Paused',
    'admin.groups.completed': 'Completed',
    'admin.groups.cancelled': 'Cancelled',
    'admin.groups.members': 'Members',
    'admin.groups.amount': 'Amount',
    'admin.groups.startDate': 'Start Date',
    'admin.groups.noGroups': 'No groups found',
    'admin.groups.totalGroups': 'Total Groups',
    'admin.groups.activeGroups': 'Active Groups',
    'admin.groups.totalMembers': 'Total Members',

    'admin.messages.title': 'Contact Messages',
    'admin.messages.subtitle': 'View and respond to user inquiries',
    'admin.messages.allMessages': 'All Messages',
    'admin.messages.new': 'New',
    'admin.messages.read': 'Read',
    'admin.messages.replied': 'Replied',
    'admin.messages.noMessages': 'No messages found',
    'admin.messages.message': 'Message',
    'admin.messages.response': 'Your Response',
    'admin.messages.respondedAt': 'Responded at',
    'admin.messages.writeResponse': 'Write Response',
    'admin.messages.responsePlaceholder': 'Type your response here...',
    'admin.messages.sendResponse': 'Send Response',
    'admin.messages.sending': 'Sending...',
    'admin.messages.selectMessage': 'Select a message to view details',
    'admin.messages.responseSuccess': 'Response sent successfully',
    'admin.messages.responseError': 'Failed to send response',

    'admin.activity.title': 'Activity Log',
    'admin.activity.subtitle': 'Track all admin actions',
    'admin.activity.allTypes': 'All Types',
    'admin.activity.timestamp': 'Timestamp',
    'admin.activity.admin': 'Admin',
    'admin.activity.action': 'Action',
    'admin.activity.targetType': 'Type',
    'admin.activity.noActivity': 'No activity logs found',
    'admin.activity.note': 'Note',
    'admin.activity.noteText': 'Activity logs are kept for audit purposes and cannot be deleted',

    'memberLogin.title': 'Member Login',
    'memberLogin.subtitle': 'Enter your Member ID to access your group',
    'memberLogin.infoTitle': 'What is a Member ID?',
    'memberLogin.infoText': 'Your Member ID is a unique code (e.g., LK-A3B9F2) provided by your group organizer. Check your email or ask your organizer if you don\'t have it.',
    'memberLogin.label': 'Member ID',
    'memberLogin.placeholder': 'LK-XXXXXX',
    'memberLogin.format': 'Format: LK-XXXXXX (case-insensitive)',
    'memberLogin.loggingIn': 'Logging in...',
    'memberLogin.loginButton': 'Login as Member',
    'memberLogin.organizerQuestion': 'Are you a group organizer?',
    'memberLogin.signInHere': 'Sign in here',
    'memberLogin.invalidFormat': 'Invalid Member ID format. Must be: LK-XXXXXX (e.g., LK-A3B9F2)',
    'memberLogin.notFound': 'Member ID not found. Please check your ID and try again.',
    'memberLogin.error': 'An error occurred during login',

    'memberPortal.welcome': 'Welcome',
    'memberPortal.memberId': 'Member ID:',
    'memberPortal.logout': 'Logout',
    'memberPortal.loading': 'Loading your portal...',
    'memberPortal.yourPosition': 'Your Position',
    'memberPortal.paymentsMade': 'Payments Made',
    'memberPortal.currentCycle': 'Current Cycle',
    'memberPortal.yourInformation': 'Your Information',
    'memberPortal.groupDetails': 'Group Details',
    'memberPortal.paymentHistory': 'Payment History',
    'memberPortal.cycle': 'Cycle',
    'memberPortal.status': 'Status',
    'memberPortal.date': 'Date',
    'memberPortal.paid': 'Paid',
    'memberPortal.notPaid': 'Not Paid',
    'memberPortal.noHistory': 'No payment history yet',
    'memberPortal.email': 'Email',
    'memberPortal.phone': 'Phone',
    'memberPortal.address': 'Address',
    'memberPortal.contributionAmount': 'Contribution Amount',
    'memberPortal.groupName': 'Group Name',
    'memberPortal.paymentMethod': 'Payment Method',
    'memberPortal.frequency': 'Frequency',
    'memberPortal.interacDetails': 'Interac Payment Details',
    'memberPortal.sendTo': 'Send to:',
  },

  fr: {
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.contact': 'Contact',
    'nav.faq': 'FAQ',
    'nav.login': 'Connexion',
    'nav.register': 'S\'inscrire',
    'nav.dashboard': 'Accueil',
    'nav.likelemba': 'Likelemba',
    'nav.members': 'Membres',
    'nav.payoutHistory': 'Historique des Paiements',
    'nav.logout': 'Déconnexion',

    'home.title': 'Construisez votre avenir grâce à',
    'home.titleHighlight': 'l\'épargne collective',
    'home.subtitle': 'Likelemba rassemble les communautés grâce aux associations d\'épargne et de crédit rotatifs traditionnels. Épargnez ensemble, grandissez ensemble, réussissez ensemble.',
    'home.getStarted': 'Commencer',
    'home.learnMore': 'En savoir plus',
    'home.whyChoose': 'Pourquoi choisir Likelemba ?',
    'home.whySubtitle': 'Découvrez la puissance de l\'épargne communautaire avec la technologie moderne',
    'home.easyManagement': 'Gestion facile',
    'home.easyManagementDesc': 'Créez et gérez vos groupes d\'épargne avec une interface intuitive. Suivez les paiements, les calendriers et les membres sans effort.',
    'home.communityDriven': 'Axé sur la communauté',
    'home.communityDrivenDesc': 'Construisez des communautés plus fortes grâce à des objectifs financiers collectifs. Soutenez-vous mutuellement tout en atteignant des objectifs individuels.',
    'home.secureReliable': 'Sécurisé et fiable',
    'home.secureReliableDesc': 'Vos données sont protégées par une sécurité de niveau entreprise. Le suivi transparent garantit la responsabilité de tous les membres.',
    'home.readyToStart': 'Prêt à commencer à épargner ?',
    'home.readySubtitle': 'Rejoignez des milliers de personnes qui utilisent Likelemba pour atteindre leurs objectifs financiers grâce à l\'épargne communautaire.',
    'home.createAccount': 'Créer votre compte',
    'home.howItWorks': 'Comment ça marche',
    'home.howItWorksSubtitle': 'Étapes simples pour commencer votre parcours d\'épargne',
    'home.step1': 'Créer un groupe',
    'home.step1Desc': 'Configurez votre groupe d\'épargne avec des paramètres personnalisés',
    'home.step2': 'Ajouter des membres',
    'home.step2Desc': 'Invitez des participants à rejoindre votre Likelemba',
    'home.step3': 'Contribuer',
    'home.step3Desc': 'Les membres font des contributions régulières selon le calendrier',
    'home.step4': 'Recevoir le paiement',
    'home.step4Desc': 'Chaque membre reçoit le montant total à tour de rôle',
    'home.visitors': 'visiteurs',

    'about.title': 'À propos de Likelemba',
    'about.subtitle': 'Autonomiser les communautés grâce aux pratiques d\'épargne traditionnelles améliorées par la technologie moderne',
    'about.whatIs': 'Qu\'est-ce que Likelemba ?',
    'about.whatIsDesc1': 'Likelemba est une plateforme numérique qui modernise le système traditionnel africain d\'association d\'épargne et de crédit rotatif (ROSCA). Le nom "Likelemba" vient du mot lingala désignant un groupe d\'épargne communautaire, une pratique profondément enracinée dans la culture africaine.',
    'about.whatIsDesc2': 'Dans un Likelemba, un groupe de personnes se réunit et contribue un montant fixe régulièrement. À chaque cycle, un membre reçoit le montant total collecté jusqu\'à ce que tout le monde en ait bénéficié. Ce système crée la confiance, encourage l\'épargne et donne accès à des sommes plus importantes sans exigences bancaires traditionnelles.',
    'about.whatIsDesc3': 'Notre plateforme amène cette pratique éprouvée à l\'ère numérique, la rendant plus facile à gérer, plus transparente et accessible aux communautés du monde entier.',
    'about.mission': 'Notre mission',
    'about.missionDesc': 'Fournir des outils accessibles, transparents et efficaces qui renforcent les liens communautaires tout en aidant les individus à atteindre leurs objectifs financiers grâce à l\'épargne collective.',
    'about.objectives': 'Nos objectifs',
    'about.objective1': 'Numériser les pratiques d\'épargne traditionnelles',
    'about.objective2': 'Accroître l\'inclusion financière',
    'about.objective3': 'Construire des communautés plus fortes',
    'about.objective4': 'Assurer la transparence et la confiance',
    'about.values': 'Nos valeurs',
    'about.communityFirst': 'La communauté d\'abord',
    'about.communityFirstDesc': 'Nous croyons au pouvoir des communautés travaillant ensemble vers des objectifs communs.',
    'about.transparency': 'Transparence',
    'about.transparencyDesc': 'Chaque transaction et calendrier est visible par tous les membres du groupe, créant la confiance.',
    'about.accessibility': 'Accessibilité',
    'about.accessibilityDesc': 'Nous rendons les outils financiers disponibles à tous, quel que soit l\'accès bancaire.',
    'about.culturalRespect': 'Respect culturel',
    'about.culturalRespectDesc': 'Nous honorons les pratiques traditionnelles tout en adoptant la technologie moderne.',
    'about.security': 'Sécurité',
    'about.securityDesc': 'Vos données et informations sont protégées par une sécurité de niveau entreprise.',
    'about.empowerment': 'Autonomisation',
    'about.empowermentDesc': 'Nous fournissons des outils qui aident les individus et les communautés à prendre le contrôle de leurs finances.',
    'about.joinCommunity': 'Rejoignez notre communauté',
    'about.joinCommunityDesc': 'Faites partie d\'un mouvement qui transforme la façon dont les communautés épargnent et se soutiennent mutuellement.',
    'about.getStartedToday': 'Commencez aujourd\'hui',

    'contact.title': 'Contactez-nous',
    'contact.subtitle': 'Vous avez des questions ? Nous aimerions vous entendre.',
    'contact.email': 'Email',
    'contact.phone': 'Téléphone',
    'contact.address': 'Adresse',
    'contact.sendMessage': 'Envoyez-nous un message',
    'contact.fullName': 'Nom complet',
    'contact.emailAddress': 'Adresse email',
    'contact.phoneNumber': 'Numéro de téléphone',
    'contact.optional': 'Optionnel',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Dites-nous comment nous pouvons vous aider...',
    'contact.sendButton': 'Envoyer le message',
    'contact.sending': 'Envoi en cours...',
    'contact.successMessage': 'Merci pour votre message ! Nous vous répondrons bientôt.',

    'login.title': 'Bon retour',
    'login.subtitle': 'Connectez-vous à votre compte Likelemba',
    'login.email': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.rememberMe': 'Se souvenir de moi',
    'login.forgotPassword': 'Mot de passe oublié ?',
    'login.signIn': 'Se connecter',
    'login.signingIn': 'Connexion en cours...',
    'login.noAccount': 'Vous n\'avez pas de compte ?',
    'login.registerHere': 'Inscrivez-vous ici',

    'register.title': 'Créer un compte',
    'register.subtitle': 'Rejoignez Likelemba et commencez à épargner ensemble',
    'register.fullName': 'Nom complet',
    'register.email': 'Adresse email',
    'register.password': 'Mot de passe',
    'register.passwordRequirement': 'Au moins 6 caractères',
    'register.confirmPassword': 'Confirmer le mot de passe',
    'register.reenterPassword': 'Ressaisissez votre mot de passe',
    'register.createAccount': 'Créer un compte',
    'register.creating': 'Création en cours...',
    'register.hasAccount': 'Vous avez déjà un compte ?',
    'register.signIn': 'Se connecter',
    'register.successMessage': 'Compte créé avec succès ! Veuillez vérifier votre email pour confirmer votre compte. Redirection vers la connexion...',

    'forgotPassword.title': 'Mot de passe oublié',
    'forgotPassword.subtitle': 'Entrez votre email pour recevoir un lien de réinitialisation',
    'forgotPassword.email': 'Adresse email',
    'forgotPassword.sendLink': 'Envoyer le lien',
    'forgotPassword.sending': 'Envoi en cours...',
    'forgotPassword.backToLogin': 'Retour à la connexion',
    'forgotPassword.successMessage': 'Le lien de réinitialisation du mot de passe a été envoyé à votre email. Veuillez vérifier votre boîte de réception et suivre les instructions.',

    'resetPassword.title': 'Réinitialiser le mot de passe',
    'resetPassword.subtitle': 'Entrez votre nouveau mot de passe ci-dessous',
    'resetPassword.newPassword': 'Nouveau mot de passe',
    'resetPassword.confirmPassword': 'Confirmer le mot de passe',
    'resetPassword.passwordHint': 'Doit contenir au moins 6 caractères',
    'resetPassword.updatePassword': 'Mettre à jour le mot de passe',
    'resetPassword.updating': 'Mise à jour...',
    'resetPassword.successMessage': 'Mot de passe mis à jour avec succès !',
    'resetPassword.redirecting': 'Redirection vers la connexion...',

    'confirmEmail.verifying': 'Vérification de votre email...',
    'confirmEmail.pleaseWait': 'Veuillez patienter pendant que nous confirmons votre adresse email',
    'confirmEmail.success': 'Email Confirmé !',
    'confirmEmail.successMessage': 'Votre email a été confirmé avec succès. Vous pouvez maintenant vous connecter à votre compte.',
    'confirmEmail.redirecting': 'Redirection vers la page de connexion...',
    'confirmEmail.error': 'Échec de la Confirmation',
    'confirmEmail.errorMessage': 'Une erreur s\'est produite lors de la confirmation de votre adresse email.',
    'confirmEmail.goToLogin': 'Aller à la Connexion',

    'dashboard.welcome': 'Bienvenue',
    'dashboard.totalGroups': 'Groupes totaux',
    'dashboard.activeGroups': 'Groupes actifs',
    'dashboard.totalMembers': 'Membres totaux',
    'dashboard.mamanStatus': 'Statut Maman Likelemba',
    'dashboard.mamanStatusDesc': 'Vous êtes un membre principal et pouvez gérer les groupes Likelemba pour votre communauté.',
    'dashboard.yourGroups': 'Vos groupes Likelemba',
    'dashboard.createGroup': 'Créer un groupe',
    'dashboard.noGroups': 'Aucun groupe pour le moment',
    'dashboard.noGroupsDesc': 'Créez votre premier groupe Likelemba pour commencer',
    'dashboard.createFirstGroup': 'Créer votre premier groupe',
    'dashboard.members': 'membres',
    'dashboard.perMember': 'par membre',
    'dashboard.started': 'Commencé',
    'dashboard.viewMembers': 'Voir les membres',
    'dashboard.loading': 'Chargement des groupes...',
    'dashboard.edit': 'Modifier',
    'dashboard.delete': 'Supprimer',
    'dashboard.share': 'Partager',
    'dashboard.editGroup': 'Modifier le groupe',
    'dashboard.deleteGroup': 'Supprimer le groupe',
    'dashboard.groupName': 'Nom du groupe',
    'dashboard.amountPerMember': 'Montant par membre ($)',
    'dashboard.paymentFrequency': 'Fréquence de paiement',
    'dashboard.paymentMethod': 'Méthode de paiement',
    'dashboard.status': 'Statut',
    'dashboard.active': 'Actif',
    'dashboard.completed': 'Terminé',
    'dashboard.paused': 'En pause',
    'dashboard.bankTransfer': 'Virement bancaire',
    'dashboard.saving': 'Enregistrement...',
    'dashboard.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer le groupe',
    'dashboard.deleteWarning': '⚠️ Cette action est irréversible. Tous les membres, paiements et historiques seront supprimés.',
    'dashboard.typeToConfirm': 'Pour confirmer, tapez le nom du groupe :',
    'dashboard.deleting': 'Suppression...',
    'dashboard.deletePermanently': 'Supprimer définitivement',

    'profile.title': 'Mon Profil',
    'profile.fullName': 'Nom complet',
    'profile.email': 'Email',
    'profile.emailNote': 'L\'email ne peut pas être modifié',
    'profile.phone': 'Téléphone',
    'profile.address': 'Adresse',
    'profile.saveChanges': 'Enregistrer les modifications',
    'profile.clickToChange': 'Cliquez sur l\'icône pour changer la photo',
    'profile.maxSize': 'Max 2MB • JPG, PNG',
    'profile.uploading': 'Téléchargement...',
    'profile.dangerZone': 'Zone dangereuse',
    'profile.deleteAccount': 'Supprimer mon compte',
    'profile.deleteWarning': 'La suppression de votre compte est permanente et ne peut pas être annulée. Toutes vos données seront supprimées définitivement.',
    'profile.deleteConfirmTitle': 'Confirmer la suppression',
    'profile.deleteConfirmText': 'Cette action est irréversible. Toutes vos données, groupes et historiques seront supprimés définitivement.',
    'profile.typeDELETE': 'Pour confirmer, tapez DELETE ci-dessous :',
    'profile.deletingAccount': 'Suppression...',

    'likelemba.title': 'Créer un groupe Likelemba',
    'likelemba.subtitle': 'Configurez un nouveau groupe d\'épargne pour votre communauté',
    'likelemba.groupName': 'Nom du groupe',
    'likelemba.groupNamePlaceholder': 'ex: Groupe d\'épargne communautaire',
    'likelemba.numberOfMembers': 'Nombre de membres',
    'likelemba.amountPerMember': 'Montant par membre ($)',
    'likelemba.paymentFrequency': 'Fréquence de paiement',
    'likelemba.daily': 'Quotidien',
    'likelemba.weekly': 'Hebdomadaire',
    'likelemba.monthly': 'Mensuel',
    'likelemba.paymentMethod': 'Méthode de paiement',
    'likelemba.interac': 'Interac',
    'likelemba.cash': 'Espèces',
    'likelemba.startDate': 'Date de début',
    'likelemba.endDate': 'Date de fin',
    'likelemba.summary': 'Résumé',
    'likelemba.totalPerCycle': 'Total par cycle :',
    'likelemba.serviceFee': 'Frais de service (unique) :',
    'likelemba.receiveNote': 'Chaque membre recevra',
    'likelemba.whenTurn': 'quand ce sera son tour',
    'likelemba.createButton': 'Créer le groupe',
    'likelemba.creating': 'Création en cours...',

    'members.title': 'Membres',
    'members.noGroupSelected': 'Aucun groupe sélectionné',
    'members.selectGroup': 'Veuillez sélectionner un groupe depuis votre tableau de bord',
    'members.addMember': 'Ajouter un membre',
    'members.noMembers': 'Aucun membre pour le moment',
    'members.addFirstMember': 'Ajouter le premier membre',
    'members.position': 'Position',
    'members.contribution': 'contribution',
    'members.paid': 'Payé',
    'members.recordPayment': 'Enregistrer le paiement',
    'members.processing': 'Traitement...',
    'members.editMember': 'Modifier le membre',
    'members.fullName': 'Nom complet',
    'members.email': 'Email',
    'members.phone': 'Téléphone',
    'members.address': 'Adresse',
    'members.membershipAmount': 'Montant d\'adhésion ($)',
    'members.receiptOrder': 'Ordre de réception',
    'members.cancel': 'Annuler',
    'members.update': 'Mettre à jour',
    'members.add': 'Ajouter',
    'members.cycle': 'Cycle',
    'members.nextPayment': 'Prochain paiement :',
    'members.loading': 'Chargement...',

    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.yes': 'Oui',
    'common.no': 'Non',

    'payment.title': 'Suivi des paiements',
    'payment.contributions': 'Contributions',
    'payment.totalPaid': 'Total payé',
    'payment.ofPayments': 'sur {total} paiements',
    'payment.completion': 'Achèvement',
    'payment.overallProgress': 'progression globale',
    'payment.periods': 'Périodes',
    'payment.cycles': 'cycles',
    'payment.current': 'Actuel',
    'payment.cycle': 'Cycle',
    'payment.paid': 'payé',
    'payment.markPaid': 'Marquer comme payé',
    'payment.sending': 'Envoi...',
    'payment.remind': 'Rappeler',
    'payment.sent': 'Envoyé',
    'payment.noGroupSelected': 'Aucun groupe sélectionné',
    'payment.selectGroup': 'Veuillez sélectionner un groupe depuis votre tableau de bord',
    'payment.noPeriods': 'Aucune période de paiement trouvée pour ce groupe',
    'payment.daily': 'Quotidien',
    'payment.weekly': 'Hebdomadaire',
    'payment.monthly': 'Mensuel',
    'payment.reminderSent': 'Rappel envoyé à {name}',
    'payment.reminderFailed': 'Échec de l\'envoi du rappel',
    'payment.updateFailed': 'Échec de la mise à jour du statut de paiement',

    'shared.invalidLink': 'Lien de partage invalide',
    'shared.notFound': 'Groupe introuvable ou lien expiré',
    'shared.loadFailed': 'Échec du chargement des données du groupe',
    'shared.paymentsTitle': 'Membres et paiements',
    'shared.noPayments': 'Aucun paiement enregistré',
    'shared.sharedBy': 'Ce lien a été partagé par le gestionnaire du groupe Likelemba',

    'search.placeholder': 'Rechercher des groupes...',
    'search.noResults': 'Aucun groupe trouvé',
    'search.tryAdjusting': 'Essayez d\'ajuster votre requête de recherche',

    'nav.profile': 'Profil',
    'nav.paymentTracking': 'Suivi des paiements',

    'share.buttonText': 'Partager',
    'share.title': 'Partager le groupe',
    'share.description': 'Partagez ce lien avec les membres de votre groupe. Ils pourront voir tous les membres et l\'historique des paiements.',
    'share.activeLink': 'Lien de partage actif',
    'share.copied': 'Copié!',
    'share.copyLink': 'Copier le lien',
    'share.generateNew': 'Générer un nouveau lien',
    'share.generating': 'Génération...',
    'share.generate': 'Générer un lien de partage',
    'share.warning': '💡 Ce lien permet à n\'importe qui de voir les informations du groupe et l\'historique des paiements. Ne le partagez qu\'avec les membres de votre groupe.',
    'share.error': 'Erreur lors de la création du lien de partage',

    'notification.title': 'Rappels de paiement',
    'notification.unread': '{count} notification non lue',
    'notification.unreadPlural': '{count} notifications non lues',
    'notification.dismiss': 'Ignorer',
    'notification.cycle': 'Cycle {number}',
    'notification.payTo': 'Payer {name}',
    'notification.markRead': 'Marquer comme lu',
    'notification.showLess': 'Montrer moins',
    'notification.showMore': 'Montrer {count} de plus',
    'notification.today': 'Aujourd\'hui',
    'notification.tomorrow': 'Demain',

    'footer.copyright': 'Tous droits réservés.',
    'footer.tagline': 'Construire des communautés grâce à l\'épargne collective',

    'faq.title': 'Questions Fréquemment Posées',
    'faq.subtitle': 'Obtenez des réponses instantanées à vos questions sur Likelemba',
    'faq.aiAssistant': 'Assistant IA',
    'faq.askPlaceholder': 'Demandez-moi n\'importe quoi sur Likelemba...',
    'faq.ask': 'Demander',
    'faq.asking': 'En cours...',
    'faq.loginPrompt': 'Connectez-vous pour enregistrer l\'historique de vos conversations et obtenir des réponses personnalisées',
    'faq.showChat': 'Afficher l\'historique',
    'faq.hideChat': 'Masquer le chat',
    'faq.thinking': 'Réflexion...',
    'faq.wasHelpful': 'Cela a-t-il été utile ?',
    'faq.browseFAQs': 'Parcourir les FAQ',
    'faq.searchPlaceholder': 'Rechercher dans les FAQ...',
    'faq.all': 'Tout',
    'faq.noResults': 'Aucune FAQ correspondant à votre recherche',
    'faq.stillQuestions': 'Vous avez encore des questions ?',
    'faq.contactSupport': 'Contacter le support',

    'payoutHistory.title': 'Historique des Paiements',
    'payoutHistory.subtitle': 'Suivez quels membres ont reçu leurs paiements à chaque cycle',
    'payoutHistory.selectGroup': 'Sélectionner un Groupe',
    'payoutHistory.members': 'membres',
    'payoutHistory.noGroups': 'Aucun groupe trouvé',
    'payoutHistory.noGroupsDesc': 'Créez un groupe Likelemba pour commencer à suivre les paiements',
    'payoutHistory.noCycles': 'Aucun cycle pour le moment',
    'payoutHistory.noCyclesDesc': 'Les cycles de paiement apparaîtront ici une fois votre groupe démarré',
    'payoutHistory.cycle': 'Cycle',
    'payoutHistory.beneficiary': 'Bénéficiaire',
    'payoutHistory.paymentDate': 'Date de Paiement',
    'payoutHistory.totalAmount': 'Montant Total',
    'payoutHistory.contributions': 'Contributions',
    'payoutHistory.status': 'Statut',
    'payoutHistory.completed': 'Terminé',
    'payoutHistory.pending': 'En attente',
    'payoutHistory.overdue': 'En retard',
    'payoutHistory.howItWorks': 'Comment fonctionne l\'historique des paiements',
    'payoutHistory.howItWorksLine1': 'Chaque cycle représente un tour de contributions où un membre reçoit le montant total collecté',
    'payoutHistory.howItWorksLine2': 'Le bénéficiaire est déterminé par l\'ordre de réception défini lors de la création du groupe',
    'payoutHistory.howItWorksLine3': 'Les contributions montrent combien de membres ont payé pour ce cycle',
    'payoutHistory.howItWorksLine4': 'Le statut indique si le paiement est terminé, en attente ou en retard',

    'memberLogin.title': 'Connexion Membre',
    'memberLogin.subtitle': 'Entrez votre ID de membre pour accéder à votre groupe',
    'memberLogin.infoTitle': 'Qu\'est-ce qu\'un ID de membre ?',
    'memberLogin.infoText': 'Votre ID de membre est un code unique (par exemple, LK-A3B9F2) fourni par l\'organisateur de votre groupe. Vérifiez votre email ou demandez à votre organisateur si vous ne l\'avez pas.',
    'memberLogin.label': 'ID de Membre',
    'memberLogin.placeholder': 'LK-XXXXXX',
    'memberLogin.format': 'Format : LK-XXXXXX (insensible à la casse)',
    'memberLogin.loggingIn': 'Connexion en cours...',
    'memberLogin.loginButton': 'Se connecter en tant que membre',
    'memberLogin.organizerQuestion': 'Êtes-vous un organisateur de groupe ?',
    'memberLogin.signInHere': 'Connectez-vous ici',
    'memberLogin.invalidFormat': 'Format d\'ID de membre invalide. Doit être : LK-XXXXXX (par exemple, LK-A3B9F2)',
    'memberLogin.notFound': 'ID de membre introuvable. Veuillez vérifier votre ID et réessayer.',
    'memberLogin.error': 'Une erreur s\'est produite lors de la connexion',

    'memberPortal.welcome': 'Bienvenue',
    'memberPortal.memberId': 'ID de Membre :',
    'memberPortal.logout': 'Se déconnecter',
    'memberPortal.loading': 'Chargement de votre portail...',
    'memberPortal.yourPosition': 'Votre Position',
    'memberPortal.paymentsMade': 'Paiements Effectués',
    'memberPortal.currentCycle': 'Cycle Actuel',
    'memberPortal.yourInformation': 'Vos Informations',
    'memberPortal.groupDetails': 'Détails du Groupe',
    'memberPortal.paymentHistory': 'Historique des Paiements',
    'memberPortal.cycle': 'Cycle',
    'memberPortal.status': 'Statut',
    'memberPortal.date': 'Date',
    'memberPortal.paid': 'Payé',
    'memberPortal.notPaid': 'Non Payé',
    'memberPortal.noHistory': 'Aucun historique de paiement pour le moment',
    'memberPortal.email': 'Email',
    'memberPortal.phone': 'Téléphone',
    'memberPortal.address': 'Adresse',
    'memberPortal.contributionAmount': 'Montant de Contribution',
    'memberPortal.groupName': 'Nom du Groupe',
    'memberPortal.paymentMethod': 'Méthode de Paiement',
    'memberPortal.frequency': 'Fréquence',
    'memberPortal.interacDetails': 'Détails de Paiement Interac',
    'memberPortal.sendTo': 'Envoyer à :',
  },

  ar: {
    'nav.home': 'الرئيسية',
    'nav.about': 'عن المنصة',
    'nav.contact': 'اتصل بنا',
    'nav.faq': 'الأسئلة الشائعة',
    'nav.login': 'تسجيل الدخول',
    'nav.register': 'التسجيل',
    'nav.dashboard': 'الرئيسية',
    'nav.likelemba': 'ليكيلمبا',
    'nav.members': 'الأعضاء',
    'nav.payoutHistory': 'سجل المدفوعات',
    'nav.logout': 'تسجيل الخروج',

    'home.title': 'ابنِ مستقبلك من خلال',
    'home.titleHighlight': 'الادخار الجماعي',
    'home.subtitle': 'تجمع ليكيلمبا المجتمعات معًا من خلال جمعيات الادخار والائتمان الدوارة التقليدية. ادخر معًا، انمُ معًا، انجح معًا.',
    'home.getStarted': 'ابدأ الآن',
    'home.learnMore': 'اعرف المزيد',
    'home.whyChoose': 'لماذا تختار ليكيلمبا؟',
    'home.whySubtitle': 'اختبر قوة الادخار المجتمعي بتقنية حديثة',
    'home.easyManagement': 'إدارة سهلة',
    'home.easyManagementDesc': 'أنشئ وأدر مجموعات الادخار الخاصة بك بواجهة بديهية. تتبع المدفوعات والجداول والأعضاء بسهولة.',
    'home.communityDriven': 'مدفوع بالمجتمع',
    'home.communityDrivenDesc': 'ابنِ مجتمعات أقوى من خلال الأهداف المالية الجماعية. ادعم بعضكم البعض مع تحقيق الأهداف الفردية.',
    'home.secureReliable': 'آمن وموثوق',
    'home.secureReliableDesc': 'بياناتك محمية بأمان على مستوى المؤسسات. التتبع الشفاف يضمن المساءلة لجميع الأعضاء.',
    'home.readyToStart': 'هل أنت مستعد لبدء الادخار؟',
    'home.readySubtitle': 'انضم إلى آلاف الأشخاص الذين يستخدمون ليكيلمبا لتحقيق أهدافهم المالية من خلال الادخار المجتمعي.',
    'home.createAccount': 'إنشاء حسابك',
    'home.howItWorks': 'كيف يعمل',
    'home.howItWorksSubtitle': 'خطوات بسيطة لبدء رحلة الادخار الخاصة بك',
    'home.step1': 'إنشاء مجموعة',
    'home.step1Desc': 'قم بإعداد مجموعة الادخار الخاصة بك بمعايير مخصصة',
    'home.step2': 'إضافة أعضاء',
    'home.step2Desc': 'قم بدعوة المشاركين للانضمام إلى ليكيلمبا الخاص بك',
    'home.step3': 'المساهمة',
    'home.step3Desc': 'يقوم الأعضاء بمساهمات منتظمة حسب الجدول الزمني',
    'home.step4': 'استلام الدفعة',
    'home.step4Desc': 'يحصل كل عضو على المبلغ الكامل بالتناوب',
    'home.visitors': 'زوار',

    'about.title': 'عن ليكيلمبا',
    'about.subtitle': 'تمكين المجتمعات من خلال ممارسات الادخار التقليدية المحسنة بالتكنولوجيا الحديثة',
    'about.whatIs': 'ما هي ليكيلمبا؟',
    'about.whatIsDesc1': 'ليكيلمبا هي منصة رقمية تعمل على تحديث نظام جمعية الادخار والائتمان الدوارة الأفريقية التقليدية (ROSCA). يأتي اسم "ليكيلمبا" من كلمة لينغالا لمجموعة الادخار المجتمعية، وهي ممارسة متجذرة بعمق في الثقافة الأفريقية.',
    'about.whatIsDesc2': 'في ليكيلمبا، تجتمع مجموعة من الناس وتساهم بمبلغ ثابت بشكل منتظم. في كل دورة، يحصل عضو واحد على المبلغ الإجمالي المحصل حتى يستفيد الجميع. يبني هذا النظام الثقة ويشجع على الادخار ويوفر الوصول إلى مبالغ أكبر دون متطلبات مصرفية تقليدية.',
    'about.whatIsDesc3': 'تجلب منصتنا هذه الممارسة المختبرة عبر الزمن إلى العصر الرقمي، مما يجعلها أسهل في الإدارة، وأكثر شفافية، ومتاحة للمجتمعات حول العالم.',
    'about.mission': 'مهمتنا',
    'about.missionDesc': 'توفير أدوات يسهل الوصول إليها وشفافة وفعالة تعزز الروابط المجتمعية بينما تساعد الأفراد على تحقيق أهدافهم المالية من خلال الادخار الجماعي.',
    'about.objectives': 'أهدافنا',
    'about.objective1': 'رقمنة ممارسات الادخار التقليدية',
    'about.objective2': 'زيادة الشمول المالي',
    'about.objective3': 'بناء مجتمعات أقوى',
    'about.objective4': 'ضمان الشفافية والثقة',
    'about.values': 'قيمنا',
    'about.communityFirst': 'المجتمع أولاً',
    'about.communityFirstDesc': 'نؤمن بقوة المجتمعات التي تعمل معًا نحو أهداف مشتركة.',
    'about.transparency': 'الشفافية',
    'about.transparencyDesc': 'كل معاملة وجدول زمني مرئي لجميع أعضاء المجموعة، مما يبني الثقة.',
    'about.accessibility': 'إمكانية الوصول',
    'about.accessibilityDesc': 'نجعل الأدوات المالية متاحة للجميع، بغض النظر عن الوصول المصرفي.',
    'about.culturalRespect': 'الاحترام الثقافي',
    'about.culturalRespectDesc': 'نكرم الممارسات التقليدية بينما نتبنى التكنولوجيا الحديثة.',
    'about.security': 'الأمان',
    'about.securityDesc': 'بياناتك ومعلوماتك محمية بأمان على مستوى المؤسسات.',
    'about.empowerment': 'التمكين',
    'about.empowermentDesc': 'نوفر أدوات تساعد الأفراد والمجتمعات على السيطرة على أموالهم.',
    'about.joinCommunity': 'انضم إلى مجتمعنا',
    'about.joinCommunityDesc': 'كن جزءًا من حركة تغير طريقة ادخار المجتمعات ودعمها لبعضها البعض.',
    'about.getStartedToday': 'ابدأ اليوم',

    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'هل لديك أسئلة؟ نود أن نسمع منك.',
    'contact.email': 'البريد الإلكتروني',
    'contact.phone': 'الهاتف',
    'contact.address': 'العنوان',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.fullName': 'الاسم الكامل',
    'contact.emailAddress': 'عنوان البريد الإلكتروني',
    'contact.phoneNumber': 'رقم الهاتف',
    'contact.optional': 'اختياري',
    'contact.message': 'الرسالة',
    'contact.messagePlaceholder': 'أخبرنا كيف يمكننا المساعدة...',
    'contact.sendButton': 'إرسال الرسالة',
    'contact.sending': 'جارٍ الإرسال...',
    'contact.successMessage': 'شكرًا لك على رسالتك! سنعود إليك قريبًا.',

    'login.title': 'مرحبًا بعودتك',
    'login.subtitle': 'سجل الدخول إلى حساب ليكيلمبا الخاص بك',
    'login.email': 'عنوان البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'هل نسيت كلمة المرور؟',
    'login.signIn': 'تسجيل الدخول',
    'login.signingIn': 'جارٍ تسجيل الدخول...',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.registerHere': 'سجل هنا',

    'register.title': 'إنشاء حساب',
    'register.subtitle': 'انضم إلى ليكيلمبا وابدأ الادخار معًا',
    'register.fullName': 'الاسم الكامل',
    'register.email': 'عنوان البريد الإلكتروني',
    'register.password': 'كلمة المرور',
    'register.passwordRequirement': 'على الأقل 6 أحرف',
    'register.confirmPassword': 'تأكيد كلمة المرور',
    'register.reenterPassword': 'أعد إدخال كلمة المرور',
    'register.createAccount': 'إنشاء حساب',
    'register.creating': 'جارٍ الإنشاء...',
    'register.hasAccount': 'هل لديك حساب بالفعل؟',
    'register.signIn': 'تسجيل الدخول',
    'register.successMessage': 'تم إنشاء الحساب بنجاح! يرجى التحقق من بريدك الإلكتروني لتأكيد حسابك. إعادة التوجيه إلى تسجيل الدخول...',

    'forgotPassword.title': 'نسيت كلمة المرور',
    'forgotPassword.subtitle': 'أدخل بريدك الإلكتروني لتلقي رابط إعادة تعيين كلمة المرور',
    'forgotPassword.email': 'عنوان البريد الإلكتروني',
    'forgotPassword.sendLink': 'إرسال الرابط',
    'forgotPassword.sending': 'جارٍ الإرسال...',
    'forgotPassword.backToLogin': 'العودة إلى تسجيل الدخول',
    'forgotPassword.successMessage': 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني. يرجى التحقق من صندوق الوارد الخاص بك واتباع التعليمات.',

    'resetPassword.title': 'إعادة تعيين كلمة المرور',
    'resetPassword.subtitle': 'أدخل كلمة المرور الجديدة أدناه',
    'resetPassword.newPassword': 'كلمة المرور الجديدة',
    'resetPassword.confirmPassword': 'تأكيد كلمة المرور',
    'resetPassword.passwordHint': 'يجب أن تتكون من 6 أحرف على الأقل',
    'resetPassword.updatePassword': 'تحديث كلمة المرور',
    'resetPassword.updating': 'جارٍ التحديث...',
    'resetPassword.successMessage': 'تم تحديث كلمة المرور بنجاح!',
    'resetPassword.redirecting': 'إعادة التوجيه إلى تسجيل الدخول...',

    'confirmEmail.verifying': 'جارٍ التحقق من بريدك الإلكتروني...',
    'confirmEmail.pleaseWait': 'يرجى الانتظار بينما نقوم بتأكيد عنوان بريدك الإلكتروني',
    'confirmEmail.success': 'تم تأكيد البريد الإلكتروني!',
    'confirmEmail.successMessage': 'تم تأكيد بريدك الإلكتروني بنجاح. يمكنك الآن تسجيل الدخول إلى حسابك.',
    'confirmEmail.redirecting': 'إعادة التوجيه إلى صفحة تسجيل الدخول...',
    'confirmEmail.error': 'فشل التأكيد',
    'confirmEmail.errorMessage': 'حدث خطأ أثناء تأكيد عنوان بريدك الإلكتروني.',
    'confirmEmail.goToLogin': 'الانتقال إلى تسجيل الدخول',

    'dashboard.welcome': 'مرحبًا',
    'dashboard.totalGroups': 'إجمالي المجموعات',
    'dashboard.activeGroups': 'المجموعات النشطة',
    'dashboard.totalMembers': 'إجمالي الأعضاء',
    'dashboard.mamanStatus': 'حالة ماما ليكيلمبا',
    'dashboard.mamanStatusDesc': 'أنت عضو رئيسي ويمكنك إدارة مجموعات ليكيلمبا لمجتمعك.',
    'dashboard.yourGroups': 'مجموعات ليكيلمبا الخاصة بك',
    'dashboard.createGroup': 'إنشاء مجموعة',
    'dashboard.noGroups': 'لا توجد مجموعات بعد',
    'dashboard.noGroupsDesc': 'قم بإنشاء مجموعة ليكيلمبا الأولى للبدء',
    'dashboard.createFirstGroup': 'قم بإنشاء مجموعتك الأولى',
    'dashboard.members': 'أعضاء',
    'dashboard.perMember': 'لكل عضو',
    'dashboard.started': 'بدأت',
    'dashboard.viewMembers': 'عرض الأعضاء',
    'dashboard.loading': 'جارٍ تحميل المجموعات...',
    'dashboard.edit': 'تعديل',
    'dashboard.delete': 'حذف',
    'dashboard.share': 'مشاركة',
    'dashboard.editGroup': 'تعديل المجموعة',
    'dashboard.deleteGroup': 'حذف المجموعة',
    'dashboard.groupName': 'اسم المجموعة',
    'dashboard.amountPerMember': 'المبلغ لكل عضو ($)',
    'dashboard.paymentFrequency': 'تكرار الدفع',
    'dashboard.paymentMethod': 'طريقة الدفع',
    'dashboard.status': 'الحالة',
    'dashboard.active': 'نشط',
    'dashboard.completed': 'مكتمل',
    'dashboard.paused': 'متوقف',
    'dashboard.bankTransfer': 'تحويل بنكي',
    'dashboard.saving': 'جارٍ الحفظ...',
    'dashboard.deleteConfirm': 'هل أنت متأكد من حذف المجموعة',
    'dashboard.deleteWarning': '⚠️ هذا الإجراء لا رجعة فيه. سيتم حذف جميع الأعضاء والمدفوعات والسجلات.',
    'dashboard.typeToConfirm': 'للتأكيد، اكتب اسم المجموعة:',
    'dashboard.deleting': 'جارٍ الحذف...',
    'dashboard.deletePermanently': 'حذف نهائيًا',

    'profile.title': 'ملفي الشخصي',
    'profile.fullName': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.emailNote': 'لا يمكن تغيير البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.address': 'العنوان',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.clickToChange': 'انقر على الأيقونة لتغيير الصورة',
    'profile.maxSize': 'الحد الأقصى 2MB • JPG, PNG',
    'profile.uploading': 'جارٍ الرفع...',
    'profile.dangerZone': 'منطقة الخطر',
    'profile.deleteAccount': 'حذف حسابي',
    'profile.deleteWarning': 'حذف حسابك دائم ولا يمكن التراجع عنه. سيتم حذف جميع بياناتك نهائيًا.',
    'profile.deleteConfirmTitle': 'تأكيد الحذف',
    'profile.deleteConfirmText': 'هذا الإجراء لا رجعة فيه. سيتم حذف جميع بياناتك ومجموعاتك وسجلاتك نهائيًا.',
    'profile.typeDELETE': 'للتأكيد، اكتب DELETE أدناه:',
    'profile.deletingAccount': 'جارٍ الحذف...',

    'likelemba.title': 'إنشاء مجموعة ليكيلمبا',
    'likelemba.subtitle': 'قم بإعداد مجموعة ادخار جديدة لمجتمعك',
    'likelemba.groupName': 'اسم المجموعة',
    'likelemba.groupNamePlaceholder': 'مثال: مجموعة الادخار المجتمعية',
    'likelemba.numberOfMembers': 'عدد الأعضاء',
    'likelemba.amountPerMember': 'المبلغ لكل عضو ($)',
    'likelemba.paymentFrequency': 'تكرار الدفع',
    'likelemba.daily': 'يومي',
    'likelemba.weekly': 'أسبوعي',
    'likelemba.monthly': 'شهري',
    'likelemba.paymentMethod': 'طريقة الدفع',
    'likelemba.interac': 'إنتراك',
    'likelemba.cash': 'نقدًا',
    'likelemba.startDate': 'تاريخ البدء',
    'likelemba.endDate': 'تاريخ الانتهاء',
    'likelemba.summary': 'ملخص',
    'likelemba.totalPerCycle': 'الإجمالي لكل دورة:',
    'likelemba.serviceFee': 'رسوم الخدمة (مرة واحدة):',
    'likelemba.receiveNote': 'سيحصل كل عضو على',
    'likelemba.whenTurn': 'عندما يحين دوره',
    'likelemba.createButton': 'إنشاء المجموعة',
    'likelemba.creating': 'جارٍ الإنشاء...',

    'members.title': 'الأعضاء',
    'members.noGroupSelected': 'لم يتم تحديد مجموعة',
    'members.selectGroup': 'يرجى تحديد مجموعة من لوحة التحكم الخاصة بك',
    'members.addMember': 'إضافة عضو',
    'members.noMembers': 'لا يوجد أعضاء بعد',
    'members.addFirstMember': 'إضافة العضو الأول',
    'members.position': 'الموقف',
    'members.contribution': 'المساهمة',
    'members.paid': 'مدفوع',
    'members.recordPayment': 'تسجيل الدفع',
    'members.processing': 'جارٍ المعالجة...',
    'members.editMember': 'تعديل العضو',
    'members.fullName': 'الاسم الكامل',
    'members.email': 'البريد الإلكتروني',
    'members.phone': 'الهاتف',
    'members.address': 'العنوان',
    'members.membershipAmount': 'مبلغ العضوية ($)',
    'members.receiptOrder': 'ترتيب الاستلام',
    'members.cancel': 'إلغاء',
    'members.update': 'تحديث',
    'members.add': 'إضافة',
    'members.cycle': 'الدورة',
    'members.nextPayment': 'الدفعة التالية:',
    'members.loading': 'جارٍ التحميل...',

    'common.loading': 'جارٍ التحميل...',
    'common.error': 'خطأ',
    'common.success': 'نجاح',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',

    'payment.title': 'تتبع المدفوعات',
    'payment.contributions': 'المساهمات',
    'payment.totalPaid': 'إجمالي المدفوع',
    'payment.ofPayments': 'من {total} مدفوعات',
    'payment.completion': 'الإنجاز',
    'payment.overallProgress': 'التقدم الإجمالي',
    'payment.periods': 'الفترات',
    'payment.cycles': 'الدورات',
    'payment.current': 'الحالي',
    'payment.cycle': 'الدورة',
    'payment.paid': 'مدفوع',
    'payment.markPaid': 'تحديد كمدفوع',
    'payment.sending': 'جارٍ الإرسال...',
    'payment.remind': 'تذكير',
    'payment.sent': 'تم الإرسال',
    'payment.noGroupSelected': 'لم يتم اختيار مجموعة',
    'payment.selectGroup': 'يرجى اختيار مجموعة من لوحة التحكم',
    'payment.noPeriods': 'لم يتم العثور على فترات دفع لهذه المجموعة',
    'payment.daily': 'يومي',
    'payment.weekly': 'أسبوعي',
    'payment.monthly': 'شهري',
    'payment.reminderSent': 'تم إرسال التذكير إلى {name}',
    'payment.reminderFailed': 'فشل إرسال التذكير',
    'payment.updateFailed': 'فشل تحديث حالة الدفع',

    'shared.invalidLink': 'رابط مشاركة غير صالح',
    'shared.notFound': 'المجموعة غير موجودة أو انتهت صلاحية الرابط',
    'shared.loadFailed': 'فشل تحميل بيانات المجموعة',
    'shared.paymentsTitle': 'الأعضاء والمدفوعات',
    'shared.noPayments': 'لا توجد مدفوعات مسجلة',
    'shared.sharedBy': 'تمت مشاركة هذا الرابط من قبل مدير مجموعة ليكيلمبا',

    'search.placeholder': 'البحث عن المجموعات...',
    'search.noResults': 'لم يتم العثور على مجموعات',
    'search.tryAdjusting': 'حاول تعديل استعلام البحث الخاص بك',

    'nav.profile': 'الملف الشخصي',
    'nav.paymentTracking': 'تتبع المدفوعات',

    'share.buttonText': 'مشاركة',
    'share.title': 'مشاركة المجموعة',
    'share.description': 'شارك هذا الرابط مع أعضاء مجموعتك. سيتمكنون من رؤية جميع الأعضاء وتاريخ المدفوعات.',
    'share.activeLink': 'رابط مشاركة نشط',
    'share.copied': 'تم النسخ!',
    'share.copyLink': 'نسخ الرابط',
    'share.generateNew': 'إنشاء رابط جديد',
    'share.generating': 'جارٍ الإنشاء...',
    'share.generate': 'إنشاء رابط مشاركة',
    'share.warning': '💡 يسمح هذا الرابط لأي شخص بعرض معلومات المجموعة وتاريخ المدفوعات. شاركه فقط مع أعضاء مجموعتك.',
    'share.error': 'خطأ في إنشاء رابط المشاركة',

    'notification.title': 'تذكيرات الدفع',
    'notification.unread': '{count} إشعار غير مقروء',
    'notification.unreadPlural': '{count} إشعارات غير مقروءة',
    'notification.dismiss': 'إغلاق',
    'notification.cycle': 'الدورة {number}',
    'notification.payTo': 'ادفع لـ {name}',
    'notification.markRead': 'تحديد كمقروء',
    'notification.showLess': 'عرض أقل',
    'notification.showMore': 'عرض {count} أكثر',
    'notification.today': 'اليوم',
    'notification.tomorrow': 'غدًا',

    'footer.copyright': 'جميع الحقوق محفوظة.',
    'footer.tagline': 'بناء المجتمعات من خلال الادخار الجماعي',

    'faq.title': 'الأسئلة الشائعة',
    'faq.subtitle': 'احصل على إجابات فورية لأسئلتك حول ليكيلمبا',
    'faq.aiAssistant': 'مساعد الذكاء الاصطناعي',
    'faq.askPlaceholder': 'اسألني أي شيء عن ليكيلمبا...',
    'faq.ask': 'اسأل',
    'faq.asking': 'جارٍ السؤال...',
    'faq.loginPrompt': 'قم بتسجيل الدخول لحفظ سجل محادثتك والحصول على إجابات مخصصة',
    'faq.showChat': 'عرض سجل المحادثة',
    'faq.hideChat': 'إخفاء المحادثة',
    'faq.thinking': 'جارٍ التفكير...',
    'faq.wasHelpful': 'هل كان هذا مفيدًا؟',
    'faq.browseFAQs': 'تصفح الأسئلة الشائعة',
    'faq.searchPlaceholder': 'البحث في الأسئلة الشائعة...',
    'faq.all': 'الكل',
    'faq.noResults': 'لم يتم العثور على أسئلة شائعة مطابقة لبحثك',
    'faq.stillQuestions': 'لا تزال لديك أسئلة؟',
    'faq.contactSupport': 'اتصل بالدعم',

    'payoutHistory.title': 'سجل المدفوعات',
    'payoutHistory.subtitle': 'تتبع الأعضاء الذين تلقوا مدفوعاتهم في كل دورة',
    'payoutHistory.selectGroup': 'اختر مجموعة',
    'payoutHistory.members': 'أعضاء',
    'payoutHistory.noGroups': 'لم يتم العثور على مجموعات',
    'payoutHistory.noGroupsDesc': 'أنشئ مجموعة ليكيلمبا لبدء تتبع المدفوعات',
    'payoutHistory.noCycles': 'لا توجد دورات بعد',
    'payoutHistory.noCyclesDesc': 'ستظهر دورات الدفع هنا بمجرد بدء مجموعتك',
    'payoutHistory.cycle': 'الدورة',
    'payoutHistory.beneficiary': 'المستفيد',
    'payoutHistory.paymentDate': 'تاريخ الدفع',
    'payoutHistory.totalAmount': 'المبلغ الإجمالي',
    'payoutHistory.contributions': 'المساهمات',
    'payoutHistory.status': 'الحالة',
    'payoutHistory.completed': 'مكتمل',
    'payoutHistory.pending': 'قيد الانتظار',
    'payoutHistory.overdue': 'متأخر',
    'payoutHistory.howItWorks': 'كيف يعمل سجل المدفوعات',
    'payoutHistory.howItWorksLine1': 'كل دورة تمثل جولة واحدة من المساهمات حيث يتلقى عضو واحد المبلغ الإجمالي المحصل',
    'payoutHistory.howItWorksLine2': 'يتم تحديد المستفيد من خلال ترتيب الاستلام المحدد عند إنشاء المجموعة',
    'payoutHistory.howItWorksLine3': 'تُظهر المساهمات عدد الأعضاء الذين دفعوا لتلك الدورة',
    'payoutHistory.howItWorksLine4': 'تُظهر الحالة ما إذا كان الدفع مكتملًا أو قيد الانتظار أو متأخرًا',

    'memberLogin.title': 'تسجيل دخول العضو',
    'memberLogin.subtitle': 'أدخل رقم العضوية الخاص بك للوصول إلى مجموعتك',
    'memberLogin.infoTitle': 'ما هو رقم العضوية؟',
    'memberLogin.infoText': 'رقم العضوية الخاص بك هو رمز فريد (على سبيل المثال، LK-A3B9F2) يوفره منظم المجموعة. تحقق من بريدك الإلكتروني أو اسأل منظمك إذا لم يكن لديك.',
    'memberLogin.label': 'رقم العضوية',
    'memberLogin.placeholder': 'LK-XXXXXX',
    'memberLogin.format': 'التنسيق: LK-XXXXXX (غير حساس لحالة الأحرف)',
    'memberLogin.loggingIn': 'جارٍ تسجيل الدخول...',
    'memberLogin.loginButton': 'تسجيل الدخول كعضو',
    'memberLogin.organizerQuestion': 'هل أنت منظم المجموعة؟',
    'memberLogin.signInHere': 'سجل الدخول هنا',
    'memberLogin.invalidFormat': 'تنسيق رقم العضوية غير صالح. يجب أن يكون: LK-XXXXXX (على سبيل المثال، LK-A3B9F2)',
    'memberLogin.notFound': 'رقم العضوية غير موجود. يرجى التحقق من رقمك والمحاولة مرة أخرى.',
    'memberLogin.error': 'حدث خطأ أثناء تسجيل الدخول',

    'memberPortal.welcome': 'مرحبًا',
    'memberPortal.memberId': 'رقم العضوية:',
    'memberPortal.logout': 'تسجيل الخروج',
    'memberPortal.loading': 'جارٍ تحميل البوابة الخاصة بك...',
    'memberPortal.yourPosition': 'موقعك',
    'memberPortal.paymentsMade': 'المدفوعات المنجزة',
    'memberPortal.currentCycle': 'الدورة الحالية',
    'memberPortal.yourInformation': 'معلوماتك',
    'memberPortal.groupDetails': 'تفاصيل المجموعة',
    'memberPortal.paymentHistory': 'سجل المدفوعات',
    'memberPortal.cycle': 'الدورة',
    'memberPortal.status': 'الحالة',
    'memberPortal.date': 'التاريخ',
    'memberPortal.paid': 'مدفوع',
    'memberPortal.notPaid': 'غير مدفوع',
    'memberPortal.noHistory': 'لا يوجد سجل دفع بعد',
    'memberPortal.email': 'البريد الإلكتروني',
    'memberPortal.phone': 'الهاتف',
    'memberPortal.address': 'العنوان',
    'memberPortal.contributionAmount': 'مبلغ المساهمة',
    'memberPortal.groupName': 'اسم المجموعة',
    'memberPortal.paymentMethod': 'طريقة الدفع',
    'memberPortal.frequency': 'التكرار',
    'memberPortal.interacDetails': 'تفاصيل الدفع عبر Interac',
    'memberPortal.sendTo': 'إرسال إلى:',
  },

  pt: {
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.contact': 'Contato',
    'nav.faq': 'FAQ',
    'nav.login': 'Entrar',
    'nav.register': 'Registrar',
    'nav.dashboard': 'Início',
    'nav.likelemba': 'Likelemba',
    'nav.members': 'Membros',
    'nav.payoutHistory': 'Histórico de Pagamentos',
    'nav.logout': 'Sair',

    'home.title': 'Construa seu futuro através de',
    'home.titleHighlight': 'Poupança Coletiva',
    'home.subtitle': 'Likelemba une comunidades através de associações rotativas tradicionais de poupança e crédito. Poupe junto, cresça junto, tenha sucesso junto.',
    'home.getStarted': 'Começar',
    'home.learnMore': 'Saiba Mais',
    'home.whyChoose': 'Por que escolher Likelemba?',
    'home.whySubtitle': 'Experimente o poder da poupança comunitária com tecnologia moderna',
    'home.easyManagement': 'Gestão Fácil',
    'home.easyManagementDesc': 'Crie e gerencie seus grupos de poupança com uma interface intuitiva. Acompanhe pagamentos, cronogramas e membros sem esforço.',
    'home.communityDriven': 'Impulsionado pela Comunidade',
    'home.communityDrivenDesc': 'Construa comunidades mais fortes através de objetivos financeiros coletivos. Apoiem-se mutuamente enquanto alcançam objetivos individuais.',
    'home.secureReliable': 'Seguro e Confiável',
    'home.secureReliableDesc': 'Seus dados estão protegidos com segurança de nível empresarial. O rastreamento transparente garante a responsabilidade de todos os membros.',
    'home.readyToStart': 'Pronto para começar a poupar?',
    'home.readySubtitle': 'Junte-se a milhares de pessoas usando Likelemba para alcançar seus objetivos financeiros através da poupança comunitária.',
    'home.createAccount': 'Crie sua Conta',
    'home.howItWorks': 'Como Funciona',
    'home.howItWorksSubtitle': 'Passos simples para iniciar sua jornada de poupança',
    'home.step1': 'Criar Grupo',
    'home.step1Desc': 'Configure seu grupo de poupança com parâmetros personalizados',
    'home.step2': 'Adicionar Membros',
    'home.step2Desc': 'Convide participantes para se juntarem ao seu Likelemba',
    'home.step3': 'Contribuir',
    'home.step3Desc': 'Os membros fazem contribuições regulares conforme programado',
    'home.step4': 'Receber Pagamento',
    'home.step4Desc': 'Cada membro recebe o valor total por vez',
    'home.visitors': 'visitantes',

    'about.title': 'Sobre Likelemba',
    'about.subtitle': 'Capacitando comunidades através de práticas tradicionais de poupança aprimoradas pela tecnologia moderna',
    'about.whatIs': 'O que é Likelemba?',
    'about.whatIsDesc1': 'Likelemba é uma plataforma digital que moderniza o sistema tradicional africano de associação rotativa de poupança e crédito (ROSCA). O nome "Likelemba" vem da palavra lingala para um grupo de poupança comunitária, uma prática profundamente enraizada na cultura africana.',
    'about.whatIsDesc2': 'Em um Likelemba, um grupo de pessoas se reúne e contribui com um valor fixo regularmente. A cada ciclo, um membro recebe o valor total coletado até que todos tenham se beneficiado. Este sistema constrói confiança, incentiva a poupança e fornece acesso a somas maiores de dinheiro sem requisitos bancários tradicionais.',
    'about.whatIsDesc3': 'Nossa plataforma traz esta prática testada pelo tempo para a era digital, tornando-a mais fácil de gerenciar, mais transparente e acessível a comunidades em todo o mundo.',
    'about.mission': 'Nossa Missão',
    'about.missionDesc': 'Fornecer ferramentas acessíveis, transparentes e eficientes que fortaleçam os laços comunitários enquanto ajudam os indivíduos a alcançar seus objetivos financeiros através da poupança coletiva.',
    'about.objectives': 'Nossos Objetivos',
    'about.objective1': 'Digitalizar práticas tradicionais de poupança',
    'about.objective2': 'Aumentar a inclusão financeira',
    'about.objective3': 'Construir comunidades mais fortes',
    'about.objective4': 'Garantir transparência e confiança',
    'about.values': 'Nossos Valores',
    'about.communityFirst': 'Comunidade em Primeiro Lugar',
    'about.communityFirstDesc': 'Acreditamos no poder das comunidades trabalhando juntas em direção a objetivos comuns.',
    'about.transparency': 'Transparência',
    'about.transparencyDesc': 'Cada transação e cronograma é visível para todos os membros do grupo, construindo confiança.',
    'about.accessibility': 'Acessibilidade',
    'about.accessibilityDesc': 'Tornamos as ferramentas financeiras disponíveis para todos, independentemente do acesso bancário.',
    'about.culturalRespect': 'Respeito Cultural',
    'about.culturalRespectDesc': 'Honramos as práticas tradicionais enquanto abraçamos a tecnologia moderna.',
    'about.security': 'Segurança',
    'about.securityDesc': 'Seus dados e informações estão protegidos com segurança de nível empresarial.',
    'about.empowerment': 'Empoderamento',
    'about.empowermentDesc': 'Fornecemos ferramentas que ajudam indivíduos e comunidades a assumir o controle de suas finanças.',
    'about.joinCommunity': 'Junte-se à Nossa Comunidade',
    'about.joinCommunityDesc': 'Seja parte de um movimento que está transformando como as comunidades poupam e se apoiam mutuamente.',
    'about.getStartedToday': 'Comece Hoje',

    'contact.title': 'Entre em Contato',
    'contact.subtitle': 'Tem perguntas? Adoraríamos ouvir de você.',
    'contact.email': 'Email',
    'contact.phone': 'Telefone',
    'contact.address': 'Endereço',
    'contact.sendMessage': 'Envie-nos uma Mensagem',
    'contact.fullName': 'Nome Completo',
    'contact.emailAddress': 'Endereço de Email',
    'contact.phoneNumber': 'Número de Telefone',
    'contact.optional': 'Opcional',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Diga-nos como podemos ajudar...',
    'contact.sendButton': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'contact.successMessage': 'Obrigado pela sua mensagem! Entraremos em contato em breve.',

    'login.title': 'Bem-vindo de Volta',
    'login.subtitle': 'Entre na sua conta Likelemba',
    'login.email': 'Endereço de Email',
    'login.password': 'Senha',
    'login.rememberMe': 'Lembrar-me',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.signIn': 'Entrar',
    'login.signingIn': 'Entrando...',
    'login.noAccount': 'Não tem uma conta?',
    'login.registerHere': 'Registre-se aqui',

    'register.title': 'Criar Conta',
    'register.subtitle': 'Junte-se ao Likelemba e comece a poupar junto',
    'register.fullName': 'Nome Completo',
    'register.email': 'Endereço de Email',
    'register.password': 'Senha',
    'register.passwordRequirement': 'Pelo menos 6 caracteres',
    'register.confirmPassword': 'Confirmar Senha',
    'register.reenterPassword': 'Reinsira sua senha',
    'register.createAccount': 'Criar Conta',
    'register.creating': 'Criando...',
    'register.hasAccount': 'Já tem uma conta?',
    'register.signIn': 'Entrar',
    'register.successMessage': 'Conta criada com sucesso! Por favor, verifique seu email para confirmar sua conta. Redirecionando para o login...',

    'forgotPassword.title': 'Esqueceu a Senha',
    'forgotPassword.subtitle': 'Digite seu email para receber um link de redefinição de senha',
    'forgotPassword.email': 'Endereço de Email',
    'forgotPassword.sendLink': 'Enviar Link',
    'forgotPassword.sending': 'Enviando...',
    'forgotPassword.backToLogin': 'Voltar ao Login',
    'forgotPassword.successMessage': 'O link de redefinição de senha foi enviado para seu email. Por favor, verifique sua caixa de entrada e siga as instruções.',

    'resetPassword.title': 'Redefinir Senha',
    'resetPassword.subtitle': 'Digite sua nova senha abaixo',
    'resetPassword.newPassword': 'Nova Senha',
    'resetPassword.confirmPassword': 'Confirmar Senha',
    'resetPassword.passwordHint': 'Deve ter pelo menos 6 caracteres',
    'resetPassword.updatePassword': 'Atualizar Senha',
    'resetPassword.updating': 'Atualizando...',
    'resetPassword.successMessage': 'Senha atualizada com sucesso!',
    'resetPassword.redirecting': 'Redirecionando para o login...',

    'confirmEmail.verifying': 'Verificando seu email...',
    'confirmEmail.pleaseWait': 'Por favor, aguarde enquanto confirmamos seu endereço de email',
    'confirmEmail.success': 'Email Confirmado!',
    'confirmEmail.successMessage': 'Seu email foi confirmado com sucesso. Agora você pode fazer login na sua conta.',
    'confirmEmail.redirecting': 'Redirecionando para a página de login...',
    'confirmEmail.error': 'Falha na Confirmação',
    'confirmEmail.errorMessage': 'Houve um erro ao confirmar seu endereço de email.',
    'confirmEmail.goToLogin': 'Ir para Login',

    'dashboard.welcome': 'Bem-vindo',
    'dashboard.totalGroups': 'Grupos Totais',
    'dashboard.activeGroups': 'Grupos Ativos',
    'dashboard.totalMembers': 'Membros Totais',
    'dashboard.mamanStatus': 'Status Maman Likelemba',
    'dashboard.mamanStatusDesc': 'Você é um membro principal e pode gerenciar grupos Likelemba para sua comunidade.',
    'dashboard.yourGroups': 'Seus Grupos Likelemba',
    'dashboard.createGroup': 'Criar Grupo',
    'dashboard.noGroups': 'Nenhum Grupo Ainda',
    'dashboard.noGroupsDesc': 'Crie seu primeiro grupo Likelemba para começar',
    'dashboard.createFirstGroup': 'Crie Seu Primeiro Grupo',
    'dashboard.members': 'membros',
    'dashboard.perMember': 'por membro',
    'dashboard.started': 'Iniciado',
    'dashboard.viewMembers': 'Ver Membros',
    'dashboard.loading': 'Carregando grupos...',
    'dashboard.edit': 'Editar',
    'dashboard.delete': 'Excluir',
    'dashboard.share': 'Compartilhar',
    'dashboard.editGroup': 'Editar Grupo',
    'dashboard.deleteGroup': 'Excluir Grupo',
    'dashboard.groupName': 'Nome do Grupo',
    'dashboard.amountPerMember': 'Valor por Membro ($)',
    'dashboard.paymentFrequency': 'Frequência de Pagamento',
    'dashboard.paymentMethod': 'Método de Pagamento',
    'dashboard.status': 'Status',
    'dashboard.active': 'Ativo',
    'dashboard.completed': 'Concluído',
    'dashboard.paused': 'Pausado',
    'dashboard.bankTransfer': 'Transferência Bancária',
    'dashboard.saving': 'Salvando...',
    'dashboard.deleteConfirm': 'Tem certeza de que deseja excluir o grupo',
    'dashboard.deleteWarning': '⚠️ Esta ação é irreversível. Todos os membros, pagamentos e histórico serão excluídos.',
    'dashboard.typeToConfirm': 'Para confirmar, digite o nome do grupo:',
    'dashboard.deleting': 'Excluindo...',
    'dashboard.deletePermanently': 'Excluir Permanentemente',

    'profile.title': 'Meu Perfil',
    'profile.fullName': 'Nome Completo',
    'profile.email': 'Email',
    'profile.emailNote': 'O email não pode ser alterado',
    'profile.phone': 'Telefone',
    'profile.address': 'Endereço',
    'profile.saveChanges': 'Salvar Alterações',
    'profile.clickToChange': 'Clique no ícone para mudar a foto',
    'profile.maxSize': 'Máx 2MB • JPG, PNG',
    'profile.uploading': 'Enviando...',
    'profile.dangerZone': 'Zona de Perigo',
    'profile.deleteAccount': 'Excluir Minha Conta',
    'profile.deleteWarning': 'Excluir sua conta é permanente e não pode ser desfeito. Todos os seus dados serão excluídos permanentemente.',
    'profile.deleteConfirmTitle': 'Confirmar Exclusão',
    'profile.deleteConfirmText': 'Esta ação é irreversível. Todos os seus dados, grupos e histórico serão excluídos permanentemente.',
    'profile.typeDELETE': 'Para confirmar, digite DELETE abaixo:',
    'profile.deletingAccount': 'Excluindo...',

    'likelemba.title': 'Criar Grupo Likelemba',
    'likelemba.subtitle': 'Configure um novo grupo de poupança para sua comunidade',
    'likelemba.groupName': 'Nome do Grupo',
    'likelemba.groupNamePlaceholder': 'ex: Grupo de Poupança Comunitária',
    'likelemba.numberOfMembers': 'Número de Membros',
    'likelemba.amountPerMember': 'Valor por Membro ($)',
    'likelemba.paymentFrequency': 'Frequência de Pagamento',
    'likelemba.daily': 'Diário',
    'likelemba.weekly': 'Semanal',
    'likelemba.monthly': 'Mensal',
    'likelemba.paymentMethod': 'Método de Pagamento',
    'likelemba.interac': 'Interac',
    'likelemba.cash': 'Dinheiro',
    'likelemba.startDate': 'Data de Início',
    'likelemba.endDate': 'Data de Término',
    'likelemba.summary': 'Resumo',
    'likelemba.totalPerCycle': 'Total por ciclo:',
    'likelemba.serviceFee': 'Taxa de serviço (única):',
    'likelemba.receiveNote': 'Cada membro receberá',
    'likelemba.whenTurn': 'quando for sua vez',
    'likelemba.createButton': 'Criar Grupo',
    'likelemba.creating': 'Criando...',

    'members.title': 'Membros',
    'members.noGroupSelected': 'Nenhum Grupo Selecionado',
    'members.selectGroup': 'Por favor, selecione um grupo do seu painel',
    'members.addMember': 'Adicionar Membro',
    'members.noMembers': 'Nenhum membro ainda',
    'members.addFirstMember': 'Adicionar Primeiro Membro',
    'members.position': 'Posição',
    'members.contribution': 'contribuição',
    'members.paid': 'Pago',
    'members.recordPayment': 'Registrar Pagamento',
    'members.processing': 'Processando...',
    'members.editMember': 'Editar Membro',
    'members.fullName': 'Nome Completo',
    'members.email': 'Email',
    'members.phone': 'Telefone',
    'members.address': 'Endereço',
    'members.membershipAmount': 'Valor da Adesão ($)',
    'members.receiptOrder': 'Ordem de Recebimento',
    'members.cancel': 'Cancelar',
    'members.update': 'Atualizar',
    'members.add': 'Adicionar',
    'members.cycle': 'Ciclo',
    'members.nextPayment': 'Próximo pagamento:',
    'members.loading': 'Carregando...',

    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.close': 'Fechar',
    'common.confirm': 'Confirmar',
    'common.yes': 'Sim',
    'common.no': 'Não',

    'payment.title': 'Rastreamento de Pagamentos',
    'payment.contributions': 'Contribuições',
    'payment.totalPaid': 'Total Pago',
    'payment.ofPayments': 'de {total} pagamentos',
    'payment.completion': 'Conclusão',
    'payment.overallProgress': 'progresso geral',
    'payment.periods': 'Períodos',
    'payment.cycles': 'ciclos',
    'payment.current': 'Atual',
    'payment.cycle': 'Ciclo',
    'payment.paid': 'pago',
    'payment.markPaid': 'Marcar como Pago',
    'payment.sending': 'Enviando...',
    'payment.remind': 'Lembrar',
    'payment.sent': 'Enviado',
    'payment.noGroupSelected': 'Nenhum Grupo Selecionado',
    'payment.selectGroup': 'Por favor, selecione um grupo do seu painel',
    'payment.noPeriods': 'Nenhum período de pagamento encontrado para este grupo',
    'payment.daily': 'Diário',
    'payment.weekly': 'Semanal',
    'payment.monthly': 'Mensal',
    'payment.reminderSent': 'Lembrete enviado para {name}',
    'payment.reminderFailed': 'Falha ao enviar lembrete',
    'payment.updateFailed': 'Falha ao atualizar status de pagamento',

    'shared.invalidLink': 'Link de compartilhamento inválido',
    'shared.notFound': 'Grupo não encontrado ou link expirado',
    'shared.loadFailed': 'Falha ao carregar dados do grupo',
    'shared.paymentsTitle': 'Membros e Pagamentos',
    'shared.noPayments': 'Nenhum pagamento registrado',
    'shared.sharedBy': 'Este link foi compartilhado pelo gerente do grupo Likelemba',

    'search.placeholder': 'Pesquisar grupos...',
    'search.noResults': 'Nenhum grupo encontrado',
    'search.tryAdjusting': 'Tente ajustar sua consulta de pesquisa',

    'nav.profile': 'Perfil',
    'nav.paymentTracking': 'Rastreamento de Pagamentos',

    'share.buttonText': 'Compartilhar',
    'share.title': 'Compartilhar Grupo',
    'share.description': 'Compartilhe este link com os membros do seu grupo. Eles poderão ver todos os membros e o histórico de pagamentos.',
    'share.activeLink': 'Link de compartilhamento ativo',
    'share.copied': 'Copiado!',
    'share.copyLink': 'Copiar Link',
    'share.generateNew': 'Gerar Novo Link',
    'share.generating': 'Gerando...',
    'share.generate': 'Gerar Link de Compartilhamento',
    'share.warning': '💡 Este link permite que qualquer pessoa veja as informações do grupo e o histórico de pagamentos. Compartilhe apenas com os membros do seu grupo.',
    'share.error': 'Erro ao criar link de compartilhamento',

    'notification.title': 'Lembretes de Pagamento',
    'notification.unread': '{count} notificação não lida',
    'notification.unreadPlural': '{count} notificações não lidas',
    'notification.dismiss': 'Dispensar',
    'notification.cycle': 'Ciclo {number}',
    'notification.payTo': 'Pagar {name}',
    'notification.markRead': 'Marcar como lido',
    'notification.showLess': 'Mostrar menos',
    'notification.showMore': 'Mostrar {count} mais',
    'notification.today': 'Hoje',
    'notification.tomorrow': 'Amanhã',

    'footer.copyright': 'Todos os direitos reservados.',
    'footer.tagline': 'Construindo comunidades através da poupança coletiva',

    'faq.title': 'Perguntas Frequentes',
    'faq.subtitle': 'Obtenha respostas instantâneas às suas perguntas sobre Likelemba',
    'faq.aiAssistant': 'Assistente IA',
    'faq.askPlaceholder': 'Pergunte-me qualquer coisa sobre Likelemba...',
    'faq.ask': 'Perguntar',
    'faq.asking': 'Perguntando...',
    'faq.loginPrompt': 'Faça login para salvar seu histórico de conversas e obter respostas personalizadas',
    'faq.showChat': 'Mostrar Histórico',
    'faq.hideChat': 'Ocultar Chat',
    'faq.thinking': 'Pensando...',
    'faq.wasHelpful': 'Isso foi útil?',
    'faq.browseFAQs': 'Navegar pelas FAQs',
    'faq.searchPlaceholder': 'Pesquisar FAQs...',
    'faq.all': 'Todos',
    'faq.noResults': 'Nenhuma FAQ correspondente à sua pesquisa',
    'faq.stillQuestions': 'Ainda tem perguntas?',
    'faq.contactSupport': 'Contatar Suporte',

    'payoutHistory.title': 'Histórico de Pagamentos',
    'payoutHistory.subtitle': 'Acompanhe quais membros receberam seus pagamentos em cada ciclo',
    'payoutHistory.selectGroup': 'Selecionar Grupo',
    'payoutHistory.members': 'membros',
    'payoutHistory.noGroups': 'Nenhum grupo encontrado',
    'payoutHistory.noGroupsDesc': 'Crie um grupo Likelemba para começar a rastrear pagamentos',
    'payoutHistory.noCycles': 'Ainda não há ciclos',
    'payoutHistory.noCyclesDesc': 'Os ciclos de pagamento aparecerão aqui assim que seu grupo começar',
    'payoutHistory.cycle': 'Ciclo',
    'payoutHistory.beneficiary': 'Beneficiário',
    'payoutHistory.paymentDate': 'Data de Pagamento',
    'payoutHistory.totalAmount': 'Valor Total',
    'payoutHistory.contributions': 'Contribuições',
    'payoutHistory.status': 'Status',
    'payoutHistory.completed': 'Concluído',
    'payoutHistory.pending': 'Pendente',
    'payoutHistory.overdue': 'Atrasado',
    'payoutHistory.howItWorks': 'Como funciona o histórico de pagamentos',
    'payoutHistory.howItWorksLine1': 'Cada ciclo representa uma rodada de contribuições onde um membro recebe o valor total arrecadado',
    'payoutHistory.howItWorksLine2': 'O beneficiário é determinado pela ordem de recebimento definida quando o grupo foi criado',
    'payoutHistory.howItWorksLine3': 'Contribuições mostram quantos membros pagaram para esse ciclo',
    'payoutHistory.howItWorksLine4': 'O status mostra se o pagamento está concluído, pendente ou atrasado',

    'memberLogin.title': 'Login de Membro',
    'memberLogin.subtitle': 'Digite seu ID de membro para acessar seu grupo',
    'memberLogin.infoTitle': 'O que é um ID de membro?',
    'memberLogin.infoText': 'Seu ID de membro é um código único (por exemplo, LK-A3B9F2) fornecido pelo organizador do seu grupo. Verifique seu e-mail ou pergunte ao seu organizador se não o tiver.',
    'memberLogin.label': 'ID de Membro',
    'memberLogin.placeholder': 'LK-XXXXXX',
    'memberLogin.format': 'Formato: LK-XXXXXX (não diferencia maiúsculas de minúsculas)',
    'memberLogin.loggingIn': 'Entrando...',
    'memberLogin.loginButton': 'Entrar como Membro',
    'memberLogin.organizerQuestion': 'Você é um organizador de grupo?',
    'memberLogin.signInHere': 'Entre aqui',
    'memberLogin.invalidFormat': 'Formato de ID de membro inválido. Deve ser: LK-XXXXXX (por exemplo, LK-A3B9F2)',
    'memberLogin.notFound': 'ID de membro não encontrado. Verifique seu ID e tente novamente.',
    'memberLogin.error': 'Ocorreu um erro durante o login',

    'memberPortal.welcome': 'Bem-vindo',
    'memberPortal.memberId': 'ID de Membro:',
    'memberPortal.logout': 'Sair',
    'memberPortal.loading': 'Carregando seu portal...',
    'memberPortal.yourPosition': 'Sua Posição',
    'memberPortal.paymentsMade': 'Pagamentos Realizados',
    'memberPortal.currentCycle': 'Ciclo Atual',
    'memberPortal.yourInformation': 'Suas Informações',
    'memberPortal.groupDetails': 'Detalhes do Grupo',
    'memberPortal.paymentHistory': 'Histórico de Pagamentos',
    'memberPortal.cycle': 'Ciclo',
    'memberPortal.status': 'Status',
    'memberPortal.date': 'Data',
    'memberPortal.paid': 'Pago',
    'memberPortal.notPaid': 'Não Pago',
    'memberPortal.noHistory': 'Ainda não há histórico de pagamentos',
    'memberPortal.email': 'Email',
    'memberPortal.phone': 'Telefone',
    'memberPortal.address': 'Endereço',
    'memberPortal.contributionAmount': 'Valor da Contribuição',
    'memberPortal.groupName': 'Nome do Grupo',
    'memberPortal.paymentMethod': 'Método de Pagamento',
    'memberPortal.frequency': 'Frequência',
    'memberPortal.interacDetails': 'Detalhes de Pagamento Interac',
    'memberPortal.sendTo': 'Enviar para:',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
